# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0003_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
