# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0004_auto_20180128_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dept',
        ),
    ]
