# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0006_auto_20180128_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=124, unique=True),
        ),
    ]
